name          'stevenmerrill-graphiteapi'
version       '0.1.0'
source        'UNKNOWN'
author        'stevenmerrill'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'stankevich/python', '1.7.x'
dependency 'stahnma/epel', '>= 0.0.6'
dependency 'ajcrowe/supervisord', '0.4.x'
